version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  test:
    executor:
      name: node/default
    parameters:
      os:
        type: string
      node-version:
        type: string
    steps:
      - checkout
      - node/install-packages
      - run: npm test

workflows:
  build:
    jobs:
      - test:
          matrix:
            parameters:
              os:
                - docker
              node-version:
                - '14.21.3'
                - '16.20.1'
                - '18.6.1'
