version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  node12:
    executor:
      name: node/default
      tag: '12.16.1'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  node10:
    executor:
      name: node/default
      tag: '10.15.0'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  node8:
    executor:
      name: node/default
      tag: '8.17.0'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
  build-and-test:
    jobs:
      - node12
      - node10
      - node8
