name: CI

on:
  push: # Run on push to all branches

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        node-version: [18, 20, 22]

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: Run Tests
        run: npm test
